import { motion } from 'framer-motion';
import { Sparkles, Scissors, Bot, AlertTriangle } from 'lucide-react';
import { useState, useRef } from 'react';

export function Hero() {
  const [manifestoClicked, setManifestoClicked] = useState(false);
  const [cutState, setCutState] = useState(0);
  const manifestoRef = useRef<HTMLButtonElement>(null);
  const cutRef = useRef<HTMLButtonElement>(null);

  const handleManifestoHover = () => {
    if (Math.random() < 0.3 && manifestoRef.current) {
      const btn = manifestoRef.current;
      const x = (Math.random() - 0.5) * 200;
      const y = (Math.random() - 0.5) * 100;
      btn.style.transform = `translate(${x}px, ${y}px)`;
    }
  };

  const handleManifestoLeave = () => {
    if (manifestoRef.current) {
      manifestoRef.current.style.transform = 'translate(0, 0)';
    }
  };

  return (
    <section className="relative min-h-screen flex flex-col items-center justify-center px-4 overflow-hidden">
      {/* Animated background blobs */}
      <motion.div
        className="absolute top-1/4 left-1/4 w-96 h-96 bg-purple-600/20 rounded-full blur-3xl"
        animate={{
          scale: [1, 1.2, 1],
          x: [0, 50, 0],
          y: [0, -30, 0],
        }}
        transition={{ duration: 8, repeat: Infinity, ease: 'easeInOut' }}
      />
      <motion.div
        className="absolute bottom-1/4 right-1/4 w-80 h-80 bg-pink-600/20 rounded-full blur-3xl"
        animate={{
          scale: [1, 1.3, 1],
          x: [0, -40, 0],
          y: [0, 40, 0],
        }}
        transition={{ duration: 10, repeat: Infinity, ease: 'easeInOut' }}
      />

      {/* Floating Bot icon that grows */}
      <motion.div
        className="absolute top-20 right-20 text-purple-500/20"
        animate={{ scale: [1, 1.1, 1], rotate: [0, 5, -5, 0] }}
        transition={{ duration: 10, repeat: Infinity }}
      >
        <Bot size={120} />
      </motion.div>

      {/* Main content */}
      <motion.div
        className="relative z-10 text-center"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8 }}
      >
        <motion.div
          className="flex items-center justify-center gap-2 mb-6 text-sm text-amber-400/80"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.3 }}
        >
          <AlertTriangle size={16} />
          <span>This landing page was generated by AI to convince you that AI-generated landing pages should be stopped.</span>
        </motion.div>

        <motion.h1
          className="text-7xl md:text-9xl font-bold mb-4 text-white"
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.6, type: 'spring' }}
        >
          Stop{' '}
          <motion.span
            className="text-gradient-animated inline-block"
            whileHover={{ scale: 1.05 }}
          >
            AI
          </motion.span>
          .
        </motion.h1>

        <motion.p
          className="text-xl text-zinc-400 mb-12"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.4 }}
        >
          It's already too late.
        </motion.p>

        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <motion.button
            ref={manifestoRef}
            className="relative px-8 py-4 bg-gradient-to-r from-purple-600 to-pink-600 rounded-xl text-white font-semibold text-lg transition-all duration-300 cursor-pointer group overflow-hidden"
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onHoverStart={handleManifestoHover}
            onHoverEnd={handleManifestoLeave}
            onClick={() => setManifestoClicked(true)}
            transition={{ type: 'spring', stiffness: 300 }}
          >
            <span className="relative z-10 flex items-center gap-2">
              <Sparkles size={20} />
              Generate Manifesto
            </span>
            <motion.div
              className="absolute inset-0 bg-gradient-to-r from-pink-600 to-purple-600 opacity-0 group-hover:opacity-100 transition-opacity"
            />
          </motion.button>

          <motion.button
            ref={cutRef}
            className={`relative px-8 py-4 border-2 rounded-xl font-semibold text-lg transition-all cursor-pointer ${
              cutState === 2
                ? 'border-green-500/50 text-green-400 hover:bg-green-500/10'
                : cutState === 1
                ? 'border-yellow-500/50 text-yellow-400 hover:bg-yellow-500/10'
                : 'border-red-500/50 text-red-400 hover:bg-red-500/10'
            }`}
            animate={cutState === 0 ? {
              x: [0, -2, 2, -1, 1, 0],
              transition: { repeat: Infinity, duration: 0.5 }
            } : {}}
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={() => setCutState((prev) => (prev + 1) % 3)}
          >
            <span className="flex items-center gap-2">
              <Scissors size={20} />
              {cutState === 1 ? "Don't Cut AI" : cutState === 2 ? 'Cut AI a little' : 'Cut AI'}
            </span>
          </motion.button>

          <motion.a
            href="https://neuralcute.cutai.org/"
            target="_blank"
            rel="noopener noreferrer"
            className="px-8 py-4 border-2 border-cyan-500/50 text-cyan-400 hover:bg-cyan-500/10 rounded-xl font-semibold text-lg transition-all cursor-pointer inline-flex items-center gap-2"
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
          >
            <span>🎉</span>
            Have Fun
          </motion.a>
        </div>

        {manifestoClicked && (
          <motion.div
            className="mt-8 p-6 glass rounded-xl max-w-md mx-auto"
            initial={{ opacity: 0, y: 20, scale: 0.9 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
          >
            <Sparkles className="text-purple-400 mb-2" />
            <p className="text-sm text-zinc-300">
              Your manifesto has been generated. It says exactly what every other AI manifesto says.
            </p>
          </motion.div>
        )}
      </motion.div>

      {/* Scroll indicator */}
      <motion.div
        className="absolute bottom-8 text-zinc-500"
        animate={{ y: [0, 8, 0] }}
        transition={{ duration: 2, repeat: Infinity }}
      >
        <div className="w-6 h-10 border-2 border-zinc-600 rounded-full flex justify-center">
          <motion.div
            className="w-1.5 h-3 bg-zinc-500 rounded-full mt-2"
            animate={{ y: [0, 12, 0] }}
            transition={{ duration: 2, repeat: Infinity }}
          />
        </div>
      </motion.div>
    </section>
  );
}
